#!/usr/bin/env ruby
#
# Copyright 2015 Apcera Inc. All rights reserved.

require_relative File.join('.', 'vagrant_helper.rb')
helper = VagrantHelper.new

Vagrant::configure('2') do |config|
	config.vm.network :public_network
  config.vm.box = "apcera/continuum_trial"
  config.vm.define :default do |default|
    helper.setup_box(default)

    default.vm.provider :vmware_fusion do |v|
      helper.fusion_options(v)
    end

    default.vm.provider :vmware_workstation do |v|
      helper.workstation_options(v)
    end

    default.vm.provider :virtualbox do |v|
      helper.virtualbox_options(v)
    end

    helper.share_folder(default)
    helper.scripts(default)
    end
end
